import * as fs from "fs";
import * as path from "path";
import { Finding, FindingCategory, FindingSeverity } from "@slopshield/shared";
import {
  StaticAnalyzer,
  AnalysisContext,
  AnalysisResult,
} from "../interfaces/static-analyzer.interface.js";

type SlopFinding = Omit<Finding, "id" | "scanId">;

interface LineRule {
  name: string;
  regex: RegExp;
  severity: FindingSeverity;
  category: FindingCategory;
  standardReferences: string[];
  whyItMatters: string;
  recommendation: string;
  /** Skip this rule in test files (mock/placeholder noise is expected there). */
  skipInTests?: boolean;
}

/**
 * Detects AI-generated "slop": placeholders, hallucination tells, copy-paste
 * artifacts, and anti-patterns. Combines precise per-line regex rules with a few
 * whole-file heuristics (function length, `any` overuse, parameter bloat) that
 * are each computed once per file to keep the pass O(lines).
 */
export class SlopAnalyzer implements StaticAnalyzer {
  public readonly name = "slop-scanner";
  public readonly description =
    "Detects common AI-generated code slop, placeholders, hallucinations, and anti-patterns";

  private readonly lineRules: LineRule[] = [
    // --- Missing / placeholder implementation ---
    {
      name: "AI Placeholder Comment",
      regex:
        /(?:\/\/|\/\*)\s*(?:TODO|FIXME|IMPLEMENT(?:ATION)?|INSERT|ADD YOUR|PLACEHOLDER|YOUR CODE HERE|CODE GOES HERE)\b/i,
      severity: "medium",
      category: "maintainability",
      standardReferences: ["CLEAN_CODE"],
      whyItMatters:
        "Placeholder comments left by AI assistants (like 'TODO: implement' or 'code goes here') indicate incomplete logic. Pushing these to production leads to broken features or dead code.",
      recommendation:
        "Complete the implementation block and remove any placeholder comments before committing.",
    },
    {
      name: "Not-Implemented Stub",
      regex:
        /throw\s+new\s+Error\(\s*['"`](?:not\s+implemented|unimplemented|todo|implement\s+me)[^'"`]*['"`]\s*\)/i,
      severity: "high",
      category: "reliability",
      standardReferences: ["CLEAN_CODE", "CODE_COMPLETE"],
      whyItMatters:
        "A 'not implemented' throw is a stub that will crash at runtime the moment the path executes. AI often scaffolds these and leaves them behind.",
      recommendation:
        "Implement the function body or remove the dead code path before shipping.",
    },
    {
      name: "Placeholder Return",
      regex:
        /return\s+(?:null|undefined|\[\]|\{\})\s*;?\s*\/\/\s*(?:placeholder|stub|todo|implement|temporary|temp)\b/i,
      severity: "medium",
      category: "reliability",
      standardReferences: ["CLEAN_CODE"],
      whyItMatters:
        "A return annotated as a placeholder signals the real logic was never written; callers silently receive empty/no data.",
      recommendation:
        "Replace the placeholder return with the intended implementation.",
    },
    {
      name: "Truncation Comment",
      regex:
        /(?:\/\/|\/\*)\s*\.\.\.\s*(?:rest of|remaining|other|more|the\s+implementation|implementation|code|logic|same as)/i,
      severity: "medium",
      category: "maintainability",
      standardReferences: ["CLEAN_CODE"],
      whyItMatters:
        "'... rest of implementation' style comments are a hallmark of an AI response pasted verbatim, where code was elided. The elided code is simply missing.",
      recommendation:
        "Restore the omitted code; never commit truncated AI output.",
    },
    // --- Conversational / copy-paste tells ---
    {
      name: "AI Conversational Hallmark",
      regex:
        /(?:\/\/|\/\*)\s*(?:hope this helps|happy coding|feel free to|fully functional|generated by AI|AI-generated|as an AI|here is the|here's the|this (?:function|code|component) (?:is|does|will)|is fully functional|let me know if)/i,
      severity: "low",
      category: "maintainability",
      standardReferences: ["CLEAN_CODE"],
      whyItMatters:
        "Conversational text or pleasantries in comments are strong indicators of unreviewed copy-pasting from chat outputs. They clutter the codebase and signal lack of developer ownership.",
      recommendation:
        "Clean up conversational comments and write concise, technical documentation instead.",
    },
    {
      name: "Trivial Debug Logging",
      regex:
        /console\.(?:log|debug|info|warn)\(\s*['"`](?:here|test+|debug|hello,?\s*world|reaches?\s*here|works?|got\s*here|checkpoint|asdf|foo|bar|xxx|\d+)['"`]\s*\)/i,
      severity: "low",
      category: "maintainability",
      standardReferences: ["CLEAN_CODE"],
      whyItMatters:
        "AI-generated code frequently inserts basic console checkpoints that log no meaningful runtime state and pollute telemetry streams.",
      recommendation:
        "Remove raw console statements or replace them with a structured logging interface.",
    },
    {
      name: "Mock Data / Fake Objects",
      regex: /const\s+\w*(?:mock|dummy|testData|mockData|fakeData|sampleData)\s*=\s*(?:\[|\{)/i,
      severity: "medium",
      category: "reliability",
      standardReferences: ["CLEAN_CODE"],
      whyItMatters:
        "Production files containing hardcoded mock data suggest that backend API integrations or dynamic client states have not been finished.",
      recommendation:
        "Replace hardcoded mock data structures with real API hooks or database queries.",
      skipInTests: true,
    },
    // --- Anti-patterns / security ---
    {
      name: "Dynamic Code Execution",
      regex: /(?<![.\w])(?:eval\s*\(|new\s+Function\s*\()/,
      severity: "high",
      category: "backend-security",
      standardReferences: ["OWASP_TOP_10", "CWE_TOP_25"],
      whyItMatters:
        "eval() and new Function() execute arbitrary strings as code, a classic injection vector. AI sometimes reaches for these instead of a safe parser.",
      recommendation:
        "Remove dynamic code execution; use JSON.parse, a lookup map, or an explicit parser instead.",
    },
    {
      name: "Empty Catch Block",
      regex: /catch\s*\([^)]*\)\s*\{\s*\}/,
      severity: "medium",
      category: "reliability",
      standardReferences: ["CLEAN_CODE", "CODE_COMPLETE"],
      whyItMatters:
        "An empty catch swallows errors silently, hiding failures from logs and users — a frequent AI shortcut that makes bugs invisible.",
      recommendation:
        "Handle, log, or rethrow the caught error; never swallow it silently.",
    },
    {
      name: "Deeply Nested Ternary",
      regex: /\?[^?:\n]*\?[^?:\n]*:[^?:\n]*:/,
      severity: "low",
      category: "maintainability",
      standardReferences: ["CLEAN_CODE", "REFACTORING"],
      whyItMatters:
        "Nested ternaries (more than two levels) are hard to read and review, and are commonly emitted by AI compressing branchy logic.",
      recommendation:
        "Refactor nested ternaries into if/else statements or a lookup table.",
    },
    {
      name: "Insecure Random for Identifiers",
      regex: /Math\.random\(\)[^;\n]*(?:id|token|key|secret|password|uuid|nonce)/i,
      severity: "medium",
      category: "backend-security",
      standardReferences: ["OWASP_TOP_10", "CWE_TOP_25"],
      whyItMatters:
        "Math.random() is not cryptographically secure; using it to derive ids/tokens/keys is predictable and unsafe.",
      recommendation:
        "Use crypto.randomUUID() or crypto.randomBytes() for security-sensitive values.",
    },
    {
      name: "Swallowed Promise Rejection",
      regex: /\.catch\(\s*\(\s*\)\s*=>\s*\{\s*\}\s*\)/,
      severity: "medium",
      category: "reliability",
      standardReferences: ["CLEAN_CODE"],
      whyItMatters:
        "An empty .catch() handler hides async failures, leaving the app in an inconsistent state with no diagnostics.",
      recommendation:
        "Log or surface the rejection; do not discard async errors.",
    },
  ];

  private readonly allowedExtensions = new Set([".ts", ".tsx", ".js", ".jsx"]);

  public async isAvailable(): Promise<boolean> {
    return true;
  }

  public async analyze(context: AnalysisContext): Promise<AnalysisResult> {
    const startTime = Date.now();
    const findings: SlopFinding[] = [];

    try {
      for (const relativeFile of context.files) {
        const ext = path.extname(relativeFile).toLowerCase();
        if (!this.allowedExtensions.has(ext)) {
          continue;
        }

        const isTestFile =
          relativeFile.includes(".test.") ||
          relativeFile.includes(".spec.") ||
          relativeFile.includes("test/") ||
          relativeFile.includes("__tests__");

        const absolutePath = path.join(context.scanDir, relativeFile);
        let stats: fs.Stats;
        try {
          stats = await fs.promises.stat(absolutePath);
        } catch {
          continue;
        }
        if (!stats.isFile()) {
          continue;
        }

        const content = await fs.promises.readFile(absolutePath, "utf8");
        const lines = content.split(/\r?\n/);

        this.runLineRules(relativeFile, lines, isTestFile, findings);
        this.runFileHeuristics(relativeFile, ext, content, lines, findings);
      }

      return {
        analyzerName: this.name,
        success: true,
        findings,
        durationMs: Date.now() - startTime,
      };
    } catch (err: any) {
      return {
        analyzerName: this.name,
        success: false,
        findings: [],
        error: err.message || String(err),
        durationMs: Date.now() - startTime,
      };
    }
  }

  private runLineRules(
    file: string,
    lines: string[],
    isTestFile: boolean,
    findings: SlopFinding[],
  ): void {
    for (let i = 0; i < lines.length; i++) {
      const lineContent = lines[i];
      for (const rule of this.lineRules) {
        if (rule.skipInTests && isTestFile) {
          continue;
        }
        if (rule.regex.test(lineContent)) {
          findings.push(this.toFinding(rule, file, i + 1, lineContent.trim()));
        }
      }
    }
  }

  /**
   * Whole-file heuristics computed in a single additional pass per file:
   * `any` overuse, generic-name overuse, long functions, parameter bloat,
   * sequential numbered variables, and oversized components.
   */
  private runFileHeuristics(
    file: string,
    ext: string,
    content: string,
    lines: string[],
    findings: SlopFinding[],
  ): void {
    // 1. `any` overuse (TypeScript only).
    if (ext === ".ts" || ext === ".tsx") {
      const anyMatches = content.match(/(?::\s*any\b|<any>|as\s+any\b|any\[\])/g);
      if (anyMatches && anyMatches.length > 3) {
        findings.push(
          this.fileFinding(
            "Excessive `any` Usage",
            "medium",
            "maintainability",
            ["CLEAN_CODE", "ISO_25010"],
            file,
            `Found ${anyMatches.length} uses of \`any\` — TypeScript's safety is largely bypassed.`,
            "Replace `any` with precise types, generics, or `unknown` with narrowing.",
          ),
        );
      }
    }

    // 2. Overly generic identifier overuse.
    const genericMatches = content.match(
      /\b(?:const|let|var)\s+(?:data|result|temp|tmp|item|thing|stuff|obj|val|value|foo|bar|res)\b/g,
    );
    if (genericMatches && genericMatches.length > 5) {
      findings.push(
        this.fileFinding(
          "Overly Generic Naming",
          "low",
          "maintainability",
          ["CLEAN_CODE"],
          file,
          `Found ${genericMatches.length} vaguely-named variables (data/result/temp/item...). Vague names are a strong AI-generation tell and hurt readability.`,
          "Rename variables to describe their domain meaning.",
        ),
      );
    }

    // 3. Sequential numbered variables (item1, item2, item3...).
    if (this.hasSequentialNumberedVars(content)) {
      findings.push(
        this.fileFinding(
          "Sequential Numbered Variables",
          "low",
          "maintainability",
          ["CLEAN_CODE", "REFACTORING"],
          file,
          "Variables like item1, item2, item3 indicate copy-paste rather than a loop or collection.",
          "Use an array and iterate instead of suffix-numbered variables.",
        ),
      );
    }

    // 4. Long functions (> 50 lines by brace span).
    for (const span of this.detectLongFunctions(lines)) {
      findings.push(
        this.fileFinding(
          "Overly Long Function",
          "low",
          "maintainability",
          ["CLEAN_CODE", "REFACTORING"],
          file,
          `A function spans ~${span.length} lines (> 50). Long functions are hard to test and review.`,
          "Extract cohesive helpers to shrink the function below ~50 lines.",
          span.startLine,
        ),
      );
    }

    // 5. Too many parameters (> 5).
    for (const hit of this.detectParamBloat(lines)) {
      findings.push(
        this.fileFinding(
          "Too Many Parameters",
          "low",
          "maintainability",
          ["CLEAN_CODE", "PHILOSOPHY_SOFTWARE_DESIGN"],
          file,
          `A function declares ${hit.count} parameters (> 5). Long parameter lists are error-prone.`,
          "Group related parameters into an options object.",
          hit.line,
        ),
      );
    }

    // 6. Oversized component/file.
    const isComponent = ext === ".tsx" || ext === ".jsx";
    if (isComponent && lines.length > 200) {
      findings.push(
        this.fileFinding(
          "Oversized Component",
          "low",
          "frontend-architecture",
          ["CLEAN_CODE", "PHILOSOPHY_SOFTWARE_DESIGN"],
          file,
          `Component file is ${lines.length} lines (> 200). Large components are hard to reason about and reuse.`,
          "Split the component into smaller composable pieces.",
        ),
      );
    }
  }

  /** True when the file contains 3+ identifiers sharing a base with sequential numeric suffixes. */
  private hasSequentialNumberedVars(content: string): boolean {
    const bases = new Map<string, Set<number>>();
    const re = /\b([a-zA-Z_]{2,})(\d)\b/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(content)) !== null) {
      const base = m[1];
      const num = Number(m[2]);
      const set = bases.get(base) ?? new Set<number>();
      set.add(num);
      bases.set(base, set);
    }
    for (const set of bases.values()) {
      const nums = [...set].sort((a, b) => a - b);
      let run = 1;
      for (let i = 1; i < nums.length; i++) {
        run = nums[i] === nums[i - 1] + 1 ? run + 1 : 1;
        if (run >= 3) {
          return true;
        }
      }
    }
    return false;
  }

  /** Estimate function spans by brace matching from each function header line. */
  private detectLongFunctions(
    lines: string[],
  ): { startLine: number; length: number }[] {
    const headerRe =
      /(?:function\s+\w+\s*\(|\b\w+\s*=\s*(?:async\s*)?\([^)]*\)\s*(?::\s*[^=]+)?=>\s*\{|\b\w+\s*\([^)]*\)\s*\{)/;
    const spans: { startLine: number; length: number }[] = [];
    for (let i = 0; i < lines.length; i++) {
      if (!headerRe.test(lines[i]) || !lines[i].includes("{")) {
        continue;
      }
      let depth = 0;
      let started = false;
      let end = i;
      for (let j = i; j < lines.length; j++) {
        for (const ch of lines[j]) {
          if (ch === "{") {
            depth++;
            started = true;
          } else if (ch === "}") {
            depth--;
          }
        }
        if (started && depth <= 0) {
          end = j;
          break;
        }
      }
      const length = end - i + 1;
      if (length > 50) {
        spans.push({ startLine: i + 1, length });
        i = end; // skip past this function to avoid nested double counting
      }
    }
    return spans;
  }

  /** Find function declarations whose parameter list has more than 5 entries. */
  private detectParamBloat(lines: string[]): { line: number; count: number }[] {
    const re = /(?:function\s+\w+|\b\w+\s*=\s*(?:async\s*)?|constructor)\s*\(([^)]*)\)/;
    const hits: { line: number; count: number }[] = [];
    for (let i = 0; i < lines.length; i++) {
      const m = re.exec(lines[i]);
      if (!m) {
        continue;
      }
      const params = m[1].trim();
      if (!params) {
        continue;
      }
      const count = params.split(",").filter((p) => p.trim().length > 0).length;
      if (count > 5) {
        hits.push({ line: i + 1, count });
      }
    }
    return hits;
  }

  private toFinding(
    rule: LineRule,
    file: string,
    line: number,
    snippet: string,
  ): SlopFinding {
    return {
      severity: rule.severity,
      category: rule.category,
      title: `AI Slop Detected: ${rule.name}`,
      file,
      line,
      standardReferences: rule.standardReferences,
      whyItMatters: rule.whyItMatters,
      recommendation: rule.recommendation,
      blocking: rule.severity === "critical",
      confidence: 0.85,
      source: "rules-engine",
      codeSnippet: snippet.slice(0, 240),
    };
  }

  private fileFinding(
    name: string,
    severity: FindingSeverity,
    category: FindingCategory,
    standardReferences: string[],
    file: string,
    whyItMatters: string,
    recommendation: string,
    line?: number,
  ): SlopFinding {
    return {
      severity,
      category,
      title: `AI Slop Detected: ${name}`,
      file,
      line,
      standardReferences,
      whyItMatters,
      recommendation,
      blocking: false,
      confidence: 0.7,
      source: "rules-engine",
    };
  }
}
