import * as fs from "fs";
import * as path from "path";
import { Finding, FindingCategory, FindingSeverity } from "@slopshield/shared";
import {
  StaticAnalyzer,
  AnalysisContext,
  AnalysisResult,
} from "../interfaces/static-analyzer.interface.js";

export class SlopAnalyzer implements StaticAnalyzer {
  public readonly name = "slop-scanner";
  public readonly description =
    "Detects common AI-generated code slop, placeholders, and hallucinations";

  private readonly patterns: {
    name: string;
    regex: RegExp;
    severity: FindingSeverity;
    category: FindingCategory;
    whyItMatters: string;
    recommendation: string;
  }[] = [
    {
      name: "AI Placeholder Comment",
      regex:
        /(?:\/\/|\/\*)\s*(?:TODO|FIXME|IMPLEMENT|INSERT|ADD YOUR|PLACEHOLDER)\b/i,
      severity: "medium",
      category: "maintainability",
      whyItMatters:
        "Placeholder comments left by AI assistants (like 'TODO: implement' or 'code goes here') indicate incomplete logic. Pushing these to production leads to broken features or dead code.",
      recommendation:
        "Complete the implementation block and remove any placeholder comments before committing.",
    },
    {
      name: "AI Conversational Hallmark",
      regex:
        /(?:\/\/|\/\*)\s*(?:hope this helps|happy coding|feel free to|fully functional|generated by AI|AI-generated|this function is|is fully functional)/i,
      severity: "low",
      category: "maintainability",
      whyItMatters:
        "Conversational text or pleasantries in comments are strong indicators of unreviewed copy-pasting from chat outputs. They clutter the codebase and signal lack of developer ownership.",
      recommendation:
        "Clean up conversational comments and write concise, technical code documentation instead.",
    },
    {
      name: "Trivial Debug Logging",
      regex:
        /console\.log\(['"](?:here|test|debug|hello world|reaches here)['"]\)/i,
      severity: "low",
      category: "maintainability",
      whyItMatters:
        "AI-generated code frequently inserts basic 'console.log' checkpoints that do not log meaningful runtime state and pollute telemetry streams.",
      recommendation:
        "Remove raw console.log statements or replace them with a structured logging interface.",
    },
    {
      name: "Mock Data / Fake Objects",
      regex: /const\s+\w*(?:mock|dummy|testData|mockData)\s*=\s*(?:\[|\{)/i,
      severity: "medium",
      category: "reliability",
      whyItMatters:
        "Production files containing hardcoded mock data suggest that backend API integrations or dynamic client states have not been finished.",
      recommendation:
        "Replace hardcoded mock data structures with real API hooks or database queries.",
    },
  ];

  private readonly allowedExtensions = new Set([".ts", ".tsx", ".js", ".jsx"]);

  public async isAvailable(): Promise<boolean> {
    return true;
  }

  public async analyze(context: AnalysisContext): Promise<AnalysisResult> {
    const startTime = Date.now();
    const findings: Omit<Finding, "id" | "scanId">[] = [];

    try {
      for (const relativeFile of context.files) {
        const ext = path.extname(relativeFile).toLowerCase();

        // Target source code files only
        if (!this.allowedExtensions.has(ext)) {
          continue;
        }

        // Skip test files for mock data check
        const isTestFile =
          relativeFile.includes(".test.") ||
          relativeFile.includes(".spec.") ||
          relativeFile.includes("test/");

        const absolutePath = path.join(context.scanDir, relativeFile);
        if (!fs.existsSync(absolutePath)) {
          continue;
        }

        const stats = fs.statSync(absolutePath);
        if (!stats.isFile()) {
          continue;
        }

        const content = fs.readFileSync(absolutePath, "utf8");
        const lines = content.split(/\r?\n/);

        for (let lineIndex = 0; lineIndex < lines.length; lineIndex++) {
          const lineContent = lines[lineIndex];

          for (const pattern of this.patterns) {
            // Skip mock data warning in test directories
            if (pattern.name === "Mock Data / Fake Objects" && isTestFile) {
              continue;
            }

            const match = lineContent.match(pattern.regex);
            if (match) {
              findings.push({
                severity: pattern.severity,
                category: pattern.category,
                title: `AI Slop Detected: ${pattern.name}`,
                file: relativeFile,
                line: lineIndex + 1,
                standardReferences: ["CLEAN_CODE"],
                whyItMatters: pattern.whyItMatters,
                recommendation: pattern.recommendation,
                blocking:
                  pattern.severity === "high" ||
                  pattern.severity === "critical",
                confidence: 0.9,
                source: "rules-engine",
                codeSnippet: lineContent.trim(),
              });
            }
          }
        }
      }

      return {
        analyzerName: this.name,
        success: true,
        findings,
        durationMs: Date.now() - startTime,
      };
    } catch (err: any) {
      return {
        analyzerName: this.name,
        success: false,
        findings: [],
        error: err.message || String(err),
        durationMs: Date.now() - startTime,
      };
    }
  }
}
